# git-tools.conf
# Formato: SCRIPT|TITULO_MENU|TITULO_LAZARUS|PARAMS

# --- Inicialização ------------------------------------------------------------
git-ini.sh|01 - Inicializar repositório (ini)|Inicializar repositório|

# --- Commits ------------------------------------------------------------------
git-feat.sh|02 - Nova funcionalidade (feat)|Adicionar funcionalidade|
git-fix.sh|03 - Correção (fix)|Corrigir problema|
git-breaking.sh|04 - Breaking change|Alteração importante|
git-refactor.sh|05 - Refatoração (refactor)|Refatorar código|
git-docs.sh|06 - Commit de documentação (docs)|Adicionar documentação|

# --- Versionamento ------------------------------------------------------------
git-version.sh|07 - Calcular próxima versão|Calcular versão|
git-version-pas-inc.sh|08 - Incrementar versão|Atualizar informações da versão para ser usada em pascal|
git-generator-lcl.sh|09 - Gerar version.inc Lazarus|Gerar versão Lazarus|

# --- Release ------------------------------------------------------------------
git-release.sh|10 - Fazer release|Gerar versão do sistema|

# --- Changelog ----------------------------------------------------------------
git-changelog.sh|11 - Gerar CHANGELOG|Git Changelog|
git-changelog-summary.sh|12 - Resumo do CHANGELOG-html|Git Changelog Resumo-html|--html


# --- Recuperação --------------------------------------------------------------
git-reset.sh|13 - Desfazer último commit (reset)|Git Reset|
git-undo-reset.sh|14 - Recuperar commit desfeito (undo reset)|Git Undo Reset|
#